apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gateboard.fullname" . }}
data:
    {{- if .Values.configMapProperties }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.configMapProperties "context" $ ) | nindent 2 }}
    {{- end }}
