apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "gateboard.fullname" . }}
rules:
- apiGroups:
  - ""
  resources:
  - 'pods'
  verbs:
  - 'get'
  - 'list'
  - 'watch'
