apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gateboard.fullname" . }}
type: Opaque
data:
  MONGO_USERNAME: {{ .Values.secrets.mongo.username }}
  MONGO_PASSWORD: {{ .Values.secrets.mongo.password }}
  MONGO_URL: {{ .Values.secrets.mongo.url }}