apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gateboard-discovery.fullname" . }}
data:
  {{- if .Values.configMapProperties }}
  {{- include "common.tplvalues.render" ( dict "value" .Values.configMapProperties "context" $ ) | nindent 2 }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gateboard-discovery.fullname" . }}-accounts
data:
  {{- if .Values.configMapAccounts }}
  {{- include "common.tplvalues.render" ( dict "value" .Values.configMapAccounts "context" $ ) | nindent 2 }}
  {{- end }}
